### ISSUE TITLE
install redis (CentOS7)

### ISSUE THREAD

**Issue by hhlvv** [hhlvv/jobro#10]
install redis

**Comment by hhlvv** [comment]
VMWare - CentOS7

redis 홈페이지(https://redis.io/download) 
$ wget http://download.redis.io/releases/redis-5.0.3.tar.gz
를 쳐봤더니,
wget : command not found 가 뜬다.

그렇다면 yum install wget을 해본다

그랬더니
loaded plugins fastestmirror you need to be root to perform this command가 떴다..
관리자 계정이 아니라 그렇다고한다.

항상 root로 접속하다 괜히 내 이름으로 된걸 만들어서 들어갔더니 이런 사단이;

다시 root로 돌아간다..
이건 어떻게 할까..
검색을 해보니 su - 를 치면 된다.
엔터치면 바로 Password: 를 입력하라고 나오고 입력하면 root로 바뀐다.

yum install wget을 했더니,
뭐라뭐라 막 뜨는데.
(cetos1)

찾아보니 /etc/resolv.conf
파일을 확인해보라고..
는 fail..
nameserver 이미 등록 되어있다ㅠㅠ

vi /etc/sysconfig/network-scripts/ifcfg-ens33 
에서 제일 아래 ONBOOT=no 를 yes로 변경

dhclient
yum update
yum install wget 
y를 한번 쳐야 complete!


다시 redis install 을 했더니 뭔가 됌.

tar xzf redis-5.0.3.tar.gz
cd redis-5.0.3
을 했더니 뭔가 바뀌었다.
make를 했더니 (4) 뭔가 된듯하다.


$ src/redis-server 
이 위치에서 
$ src/redis-cli
redis> set foo bar
OK
redis> get foo
"bar"
..src 안에 reids-server가 없다;
----> 해결중

**Comment by hhlvv** [comment]
+ VM에서 로그인 incorrect 문제 발생
===> 키보드 오류로 안되던 문제가 키보드를 바꿔도 root로그인이 안됨
https://unix.stackexchange.com/questions/358821/login-incorrect-on-centos
--> 실행법을 모르겠음...
----> http://linux.systemv.pe.kr/centos-7-%EC%8B%B1%EA%B8%80%EB%AA%A8%EB%93%9C-%EB%B6%80%ED%8C%85/

**Comment by jongfeel** [comment]
@hhlvv 
이 이슈를 closed로 하신 이유가 있나요?
여태까지 진행한 것에 대한 리뷰를 진행해 보면 좋을 것 같습니다.

**Comment by hhlvv** [comment]
- centos7 을 새로 깔고, redis를 새로 깔아서 make 한 후 다른 작업 없이 make test 를 진행 후 redis 모든 파일이 설치가 제대로 되고 작동이 되는 것을 확인했습니다.
(자세한 이미지는 블로그에 업뎃할 예정입니다)
- 비밀번호 설정 및 putty로 접속하고 방화벽을 열어두어 프로젝트에서 접속하는 부분을 확인중

**Comment by jongfeel** [comment]
@hhlvv 
노트북에서 redis-cli로 VM의 redis server에 붙어서 테스트 해보기
