### ISSUE TITLE
개발문제가 아닌 인터넷문제가 발생..

### ISSUE THREAD

**Issue by hhlvv** [hhlvv/jobro#13]
일요일 저녁경부터 그래도 잘되던 핫스팟이ㅠㅠ 노트북으로 전혀 작동하지 못하고 있네요
검색해서 네트워크 초기화, 이름 변경, 비번 변경, 다 몇번을 해봤는데도 안되네요..
아이폰이 오래되면 그럴수 있다는데
아이폰x로 바꾼지 한달 조금 되었고, 내일 아이폰의 문젠지. 통신사의 문제인지 확인을 해보고ㅠ
저녁까지 안된다면 다시 연락드릴게요
깃도 하다가 끊겨서 푸쉬도 못했고요 ㅠㅠ
푸쉬도 못하면 저녁에 나눌얘기가 없어지니...ㅠㅠ
무선 인터넷이 없는 곳도 있다는것을 제가 간과했니요... 폰에서 안되니 그저 컴퓨터도 노트패드용이네요;;

**Comment by jongfeel** [comment]
@hhlvv 

으흠 여러가지 문제가 많네요.
일단 해결이 금방되던 안되던 급하게 뭔가 하기에는 시간이 부족한건 맞으니까요.
시간을 조금 더 두고 준비해 주시면 좋을 것 같습니다.

다음 주 3월 19일에 진행해 보는 건 어떨까요?

**Comment by hhlvv** [comment]
와이파이를 다른것을 정기 결제해서 해결하였습니다/
아이폰에서 핫스팟이 일정 데이터 이상 쓰게 되면 막히는 정책이 있는데,
애플 상담사들도 아무도 몰랐던 내용이라 유심을 다른 기기에 바꿔서 테스트를 해보고,
엘지유플러스에 전화해보고 알게되었네요. 애플 상담사들이..고맙다고....첨 알았다고..... ㅠ_ㅠ
테더링 우회하는 방법도 있다고는 하나 테스트해보니 안됩니다. 뭐 이제 일단 저는 인터넷 이슈는 해결하였네요..
